[project]
name = "jax-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.13.2",
    "jax>=0.8.0",
    "numpy>=2.3.4",
    "optax>=0.2.6",
]
